{% set name = "xplique" %}
{% set version = "0.4.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/Xplique-{{ version }}.tar.gz
  sha256: d3cd6433f77168a22aaa95250b58bc38e31958a7cc593317f2f53afd9ca206a8

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - matplotlib-base
    - numpy
    - opencv
    - scikit-image
    - scikit-learn
    - scipy
    - tensorflow >=2.1.0

test:
  imports:
    - tests
    - tests.attributions
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/Xplique/
  summary: Explanations toolbox for Tensorflow 2
  license: MIT
  license_file: LICENSE
  description: |
    <b>Xplique</b> is a Python toolkit dedicated to explainability, currently based on Tensorflow.
    The goal of this library is to gather the state of the art of Explainable AI to help you understand your complex neural network models.

    PyPI: [https://pypi.org/project/Xplique/](https://pypi.org/project/Xplique/)

  doc_url: https://deel-ai.github.io/xplique/
  dev_url: https://github.com/deel-ai/xplique/

extra:
  recipe-maintainers:
    - sugatoray
