{% set name = "xplique" %}
{% set version = "1.1.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/Xplique-{{ version }}.tar.gz
  sha256: f19377c7d4f9c82237872cf59c36f2bddc983685b082cefd00284f219a93d410

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - python >={{ python_min }}
    - matplotlib-base
    - numpy
    - opencv
    - scikit-image
    - scikit-learn
    - scipy
    - tensorflow >=2.1.0

test:
  imports:
    - tests
    - tests.attributions
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://pypi.org/project/Xplique/
  summary: Explanations toolbox for Tensorflow 2
  license: MIT
  license_file: LICENSE
  description: |
    <b>Xplique</b> is a Python toolkit dedicated to explainability, currently based on Tensorflow.
    The goal of this library is to gather the state of the art of Explainable AI to help you understand your complex neural network models.

    PyPI: [https://pypi.org/project/Xplique/](https://pypi.org/project/Xplique/)

  doc_url: https://deel-ai.github.io/xplique/
  dev_url: https://github.com/deel-ai/xplique/

extra:
  recipe-maintainers:
    - sugatoray
